spring:
  #静态资源访问前缀为static
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/onlinelearn?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml
  server:
    port: 8080
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: hackerwli@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: dbvzkklpvjdmjcad
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
  web:
    resources:
      static-locations: file:D:/projects/java/onlineLearn/src/main/resources/static
  token:
    # token 签名
    secret: onlinelearn
    # token有效时长
    expire: 3600

